    <h1><i class="fas fa-bars"></i>Dashboards </h1>
    <h2>Dashboards do cliente <?= $cliente['nome'] ?></h2>
     <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>




      <div class="bloco-padrao">

        <a href="<?= $this->url('novoDashboard'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
        <br>
        <?php if($dashboards->count() > 0): ?>
        <table class="table">
          <tbody>
              <tr class="topo-tabela">
                <th style="text-align: center">Categoria</th>
                <th style="text-align: center">Nome</th>
                <th style="text-align: center">Ordem</th>
                <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($dashboards as $dashboard): ?>
                <tr>
                    <td style="text-align: center"><?= $this->caracterVazio($dashboard['nome_categoria']); ?></td>
                    <td style="text-align: center">
                      <img src="<?= $this->basePath($dashboard['icone']); ?>" style="width: 50px; height: 50px;"> <?= $dashboard['nome']; ?>
                    </td>
                    <td style="text-align: center"><?= $dashboard['ordem']; ?>º</td>
                    <td style="text-align: center;">
                        <a title="Alterar dashboard" href="<?= $this->url('alterarDashboard', array('id' => $dashboard['id'])); ?>" class="bt-editar"><i class="fas fa-edit"></i></a>
                        <a title="Deletar dashboard" onclick="alerta('<?= $this->url('deletarDashboard', array('id' => $dashboard['id'])); ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar o dashboard?');" class="bt-deletar"><i class="fas fa-minus-circle"></i></a>
                    </td>
                </tr>
              <?php endforeach; ?>
          </tbody>
        </table>
        <?php else: ?>
          <br>
          <div class="alert alert-info">Nenhuma dashboard encontrada!</div>
        <?php endif; ?>

      </div>

      <div class="paginacao">
          <?php echo $this->paginationControl($dashboards,
            'Sliding',
            'view/paginator', array('route' => 'indexDashboard')); 
          ?>
      </div>
      

