<div class="cont-admin">
  <div class="content-sistema">
    <h1><a href="<?= $this->url('indexDashboard'); ?>">Dashboards</a> / novo </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoDashboard'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <br>
      <h2>Cadastro de dashboard para o cliente <?= $cliente['nome'] ?></h2>

      <?php echo $this->partial('form/generic', array('form'=> $formDashboard, 'route'=> ''))  ?>

    </div>
  </div>
</div>