<?php if(!empty($dashboard['link_google'])): ?>
<iframe src="<?= $dashboard['link_google'] ?>" style="width: 100%; height: 600px;"></iframe>
<?php endif; ?>


<?php if(!empty($dashboard['workspace_id']) && !empty($dashboard['report_id'])): ?>
  <div id="reportContainer" style="height: 700px;"></div>
  <script>
    var embedConfiguration= {
      type: 'report',
      id: "<?= $embed['id'] ?>", // the report ID
      embedUrl: "<?= $embed['embedUrl'] ?>",
      //tokenType: models.TokenType.Embed,
      accessToken: "<?= $embed['token'] ?>" ,
    };
    var $reportContainer = $('#reportContainer');
    var report = powerbi.embed($reportContainer.get(0), embedConfiguration);
  </script>
<?php endif; ?>