<?php if(!empty($dashboard['link_google'])): ?>
<iframe src="<?= $dashboard['link_google'] ?>" style="width: 100%;height: 87%;"></iframe>
<?php endif; ?>

<?php if(!empty($dashboard['workspace_id']) && !empty($dashboard['report_id'])): ?>
  <div id="reportContainer" style="height: 87%;width: 100%;"></div>
  <script>
    var embedConfiguration= {
      type: 'report',
      id: "<?= $embed['id'] ?>", // the report ID
      embedUrl: "<?= $embed['embedUrl'] ?>",
      //tokenType: models.TokenType.Embed,
      accessToken: "<?= $embed['token'] ?>" ,
      settings: {
        filterPaneEnabled: false,
        navContentPaneEnabled: false
      },
      
    };
    var reportContainer = $('#reportContainer');
    var report = powerbi.embed(reportContainer.get(0), embedConfiguration);


    report.on('loaded', () => {
      page = 0;
      <?php if($dashboard['pagina_power_bi'] != ''): ?>
        page = <?= $dashboard['pagina_power_bi'] ?>;
      <?php endif; ?>

      report.getPages().then(pages => pages[page].setActive()); 
    });
  </script>
<?php endif; ?>