 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('usuarioNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('telaInicio'); ?>">Home</a></li>
      <li><a href="<?= $this->url('usuario'); ?>">Usuários</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title">Alteração de usuário</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formUsuario, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      var maskBehavior = function (val) {
       return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      options = {onKeyPress: function(val, e, field, options) {
       field.mask(maskBehavior.apply({}, arguments), options);
       }
      };
       
      $('#telefone').mask(maskBehavior, options);
      
      $(document).ready(function() {
        $('#cliente').attr('disabled', 'disabled');
        $('#unidade').attr('disabled', 'disabled');
      });
    </script>