<div class="bloco-login">
    
    <?php if($usuario): ?>
      <?php echo $this->partial('form/umacoluna', array('form'=> $formAtivar, 'route'=> '', 'nomeBotao' => 'Ativar usuário')) ?>  
    <?php else: ?>
      <div class="alert alert-warning" role="alert">
        Usuário não encontrado, verifique se seu link é válido ou entre em contato com o administrador.
      </div>
    <?php endif; ?>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#login').prop("disabled", true);
  });

</script>