    <h1><i class="fas fa-bars"></i>Usuários </h1>
    <h2>Lista de usuários</h2>
    <div class="conteudo-sistema">
     <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>




      <div class="bloco-padrao">

        <a href="<?= $this->url('usuarioNovoCliente'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
        <br>
        <?php if($usuarios->count() > 0): ?>
        <table class="table">
          <tbody>
              <tr class="topo-tabela">
                <th style="text-align: center">Nome</th>
                <th style="text-align: center">Login</th>
                <th style="text-align: center">Tipo</th>
                <th style="text-align: center">Status</th>
                <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($usuarios as $usuario): ?>
                <tr>
                    <td style="text-align: center"><?= $usuario['nome']; ?></td>
                    <td style="text-align: center"><?= $usuario['login']; ?></td>
                    <td style="text-align: center"><?= $usuario['perfil']; ?></td>
                    <td style="text-align: center"><?= $this->ativo($usuario['ativo']); ?></td>
                    <td style="text-align: center;">
                        <a title="Alterar usuário" href="<?= $this->url('usuarioAlterarCliente', array('id' => $usuario['id'])); ?>" class="bt-editar"><i class="fas fa-edit"></i></a>
                        <a title="Deletar usuário" onclick="alerta('<?= $this->url('deletarUsuarioCliente', array('id' => '0', 'usuario' => $usuario['id'], 'redir' => 'U')) ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar o usuário?');" class="bt-deletar"><i class="fas fa-minus-circle"></i></a>
                    </td>
                </tr>

              <?php endforeach; ?>
          </tbody>
        </table>
        <?php else: ?>
          <br>
          <div class="alert alert-info">Nenhum usuário encontrado!</div>
        <?php endif; ?>

      </div>

      <div class="paginacao">
          <?php echo $this->paginationControl($usuarios,
            'Sliding',
            'view/paginator', array('route' => 'usuarioCliente')); 
          ?>
      </div>
      

    </div>
