    <h1><i class="fas fa-bars"></i><a href="<?= $this->url('usuarioCliente'); ?>">Usuários</a> / novo </h1>
    <h2>Inserir usuário</h2>
    <div class="conteudo-sistema">
      <?php echo $this->partial('form/generic', array('form'=> $formUsuario, 'route'=> '')) ?>

    </div>
<script type="text/javascript">
  var maskBehavior = function (val) {
     return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    options = {onKeyPress: function(val, e, field, options) {
     field.mask(maskBehavior.apply({}, arguments), options);
     }
    };
     
    $('#telefone').mask(maskBehavior, options);
</script>