<div class="bloco-login">

  <form role="form" name="formLogin" action="#" method="POST" class="register-form">
      <p>
          <i class="fas fa-user"></i>
          <input type="text" name="login" id="login" class="form-control input-lg" placeholder="Email" tabindex="4">     
      </p> 

      <p>
          <input type="submit" value="Recuperar senha">
      </p>

      <p class="ac">
         <a href="<?= $this->url('login'); ?>">Logar-se</a>
      </p>        
      
  </form>   
</div>