    <h1><a href="<?= $this->url('indexCategoria'); ?>">Categorias de dashboard</a> / alterar </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoCategoria'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <br>
      <h2>Alterar categoria de dashboard do cliente <?= $cliente['nome'] ?></h2>

      <?php echo $this->partial('form/generic', array('form'=> $formCategoria, 'route'=> '')) ?>

    </div>
