    <h1><i class="fas fa-bars"></i>Categorias de dashboard</h1>
    <h2>Categorias de dashboard do cliente <?= $cliente['nome'] ?></h2>

      <div class="bloco-padrao">

        <a href="<?= $this->url('novoCategoria'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
        <br>
        <?php if($categorias->count() > 0): ?>
        <table class="table">
          <tbody>
              <tr class="topo-tabela">
                <th style="text-align: center">Nome</th>
                <th style="text-align: center">Ordem</th>
                <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($categorias as $categoria): ?>
                <tr>
                  <td style="text-align: center"><img src="<?= $this->basePath($categoria['icone']) ?>" style="width: 50px; height: 50px;"> <?= $categoria['nome']; ?></td>
                  <td style="text-align: center"><?= $categoria['ordem']; ?>º</td>
                  <td style="text-align: center;">
                      <a title="Alterar categoria" href="<?= $this->url('alterarCategoria', array('id' => $categoria['id'])); ?>" class="bt-editar"><i class="fas fa-edit"></i></a>
                      <a title="Deletar categoria" onclick="alerta('<?= $this->url('deletarCategoria', array('id' => $categoria['id'])); ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar a categoria de dashboard?');" class="bt-deletar"><i class="fas fa-minus-circle"></i></a>
                  </td>
                </tr>
              <?php endforeach; ?>
          </tbody>
        </table>
        <?php else: ?>
          <br>
          <div class="alert alert-info">Nenhuma categoria de dashboard encontrada!</div>
        <?php endif; ?>

      </div>

      <div class="paginacao">
          <?php echo $this->paginationControl($categorias,
                                      'Sliding',
                                      'view/paginator', array('route' => 'indexCategoria')); 
        ?>
      </div>