<form class="formulario campos-info" role="form" method="POST" enctype='multipart/form-data' action="#">
<?php foreach ($form->getElements() as $element): ?>
		<?php 
			$attributes = $element->getAttributes();
			if(isset($attributes['type']) && $attributes['type'] == 'hidden'){
				echo $this->formElement($element);
				continue;
			}
    ?>
    <p class="b3" id="p-form-<?=$element->getName()?>">
      <label for="<?=$element->getName()?>"><?=$element->getLabel()?></label>
      <?= $this->formElement($element); ?>
      <?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
    </p>
<?php endforeach; ?>

<p>
  <button type="submit" name="Salvar" style="float: right;" value="Salvar">
    <i class="fas fa-save"></i> Salvar
  </button>
</p>
</form>
