<?php $form->prepare(); ?>
<form role="form" name="formLogin" action="#" method="POST" class="register-form"><?php $row = 0; ?>
<?php foreach ($form->getElements() as $element): ?>
	<p>
      <i class="fas fa-user"></i>
      <?= $this->formElement($element); ?>
      <?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>      
  </p>   
  <?php endforeach; ?>
  <p>
      <input type="submit" value="<?= $this->nomeBotao ?>">
  </p>

</form>