  <form class="formulario campos-info" role="form" method="POST" action="#">
    <?php foreach ($form->getElements() as $element): ?>
      <p class="b3">
          <label for="<?=$element->getName()?>"><?=$element->getLabel()?> </label>
          <?= $this->formElement($element); ?>
          <?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
      </p> 
    <?php endforeach; ?>
    <p>
      <button type="submit" name="pesquisar" style="float: right;" value="pesquisar">
          <i class="fas fa-search"></i> Pesquisar
      </button>

      <button type="submit" name="limpar" style="float: right;margin-right: 10px;" value="limpar">
          <i class="fas fa-times"></i> Limpar
      </button>

    </p>

  </form>
  