<div class="busca">
    <form method="POST" action="#">
    <?php foreach ($form->getElements() as $element): ?>
      <p class="b3">
          <label for="<?=$element->getName()?>"><?=$element->getLabel()?> </label>
          <?= $this->formElement($element); ?>
          <?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
      </p> 
    <?php endforeach; ?>
    <p>
      <button type="submit" name="pesquisar" style="float: right;" value="pesquisar">
          <i class="fas fa-search"></i> Pesquisar
      </button>


    </p>

  </form>
</div>