<?php if ($this->pageCount): ?>
  <div class="bt-anterior">
      <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
        <i class="fas fa-angle-left"></i>
      </a>
  </div>


  <!-- Numbered page links -->
<div class="link-page">
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
      <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?= $page; ?></a> 
    <?php else: ?>
      <span><?= $page; ?></span> 
      
    <?php endif; ?>
  <?php endforeach; ?>
</div>

  <div class="bt-proximo">
      <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
          <i class="fas fa-angle-right"></i>
      </a>
  </div>


<?php endif; ?>