<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
     <?php echo $this->headTitle($this->loja['nome_restaurante'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/autocomplete.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ; ?>
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

          <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/maskMoney.js')
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/js/bootbox.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.autocomplete.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js'); ?>

  </head>
  <body>
    <div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a href="#">pro sidebar</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <a href="<?= $this->url('indexCliente'); ?>">
          <img src="<?= $this->basePath($clienteSelecionado['logo']); ?>" class="rounded mx-auto d-block" alt="Responsive image">
        </a>
        <ul>
          <li>
            <a href="<?= $this->url('visualizarDashboard'); ?>">
              <i class="fa fa-book"></i>
              <span>Dashboard 01</span>
            </a>
          </li>
          <li>
            <a href="<?= $this->url('visualizarDashboard'); ?>">
              <i class="fa fa-book"></i>
              <span>Dashboard 02</span>
            </a>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard acessos</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>"> Dashboard 1</a>
                </li>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>">  Dashboard 2</a>
                </li>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>">  Dashboard 3</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard financeiro</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>">  Dashboard 1</a>
                </li>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>">  Dashboard 2</a>
                </li>
                <li>
                  <a href="<?= $this->url('visualizarDashboard'); ?>"><img src="<?= $this->basePath('img/visualizar.png'); ?>">  Dashboard 3</a>
                </li>
              </ul>
            </div>
          </li>
          
           <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Configurações</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="<?= $this->url('indexMenu') ?>">Categorias de dashboard</a>
                </li>
                <li>
                  <a href="<?= $this->url('indexCliente'); ?>">Clientes</a>
                </li>
                <li>
                  <a href="<?= $this->url('indexDashboard') ?>">Dashboards</a>
                </li>
                <li>
                  <a href="<?= $this->url('indexInvoice') ?>">Invoices</a>
                </li>
                <li>
                  <a href="<?= $this->url('usuario'); ?>">Usuários</a>
                </li>
              </ul>
            </div>
          </li>
          <li>
            <a href="#" onclick="alert('Abre a interface de ajuda');">
              <i class="fa fa-book"></i>
              <span>Ajuda</span>
            </a>
          </li>
          <li>
            <a href="<?= $this->url('logout'); ?>">
              <i class="fa fa-book"></i>
              <span>Sair</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
  </nav>
  <!-- sidebar-wrapper  -->
  <main class="page-content">
      <div class="container theme-showcase" role="main" id="alertasLayout" style="margin-top:100px;padding: 0px;">
        <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

        <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>
        
        <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>
      </div>

      <?php echo $this->content; ?>
  </main>
  <!-- page-content" -->
</div>
    
    
  </body>




  <?php echo $this->inlineScript() ?>
  <script type="text/javascript">
    jQuery(function ($) {
      $(".sidebar-dropdown > a").click(function() {
      $(".sidebar-submenu").slideUp(200);
      if (
        $(this)
          .parent()
          .hasClass("active")
      ) {
        $(".sidebar-dropdown").removeClass("active");
        $(this)
          .parent()
          .removeClass("active");
      } else {
        $(".sidebar-dropdown").removeClass("active");
        $(this)
          .next(".sidebar-submenu")
          .slideDown(200);
        $(this)
          .parent()
          .addClass("active");
      }
    });

    $("#close-sidebar").click(function() {
      $(".page-wrapper").removeClass("toggled");
    });
    $("#show-sidebar").click(function() {
      $(".page-wrapper").addClass("toggled");
    });
  });

  </script>
</html>





