<html>
<head>
    <meta http-equiv="Content-Language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
     <?php echo $this->headTitle('Cognitive')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

          <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery_sistema.js'); ?>
            
  </head>
<body>
  <?php echo $this->content; ?>
</body>
</html>