<html>
<head>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KX356LG');</script>
    <meta http-equiv="Content-Language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="google-signin-client_id" content="119263952091-gdpfe1a4arv7dj1g2f4uia1pf517tk44.apps.googleusercontent.com">
     <?php echo $this->headTitle('Cognitive')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/sistema.css')
                        ->prependStylesheet($this->basePath() . '/css/autocomplete.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-confirm.css')
                        //->prependStylesheet($this->basePath() . '/css/sistema/colorbox.css')
                        ; ?>
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

          <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/maskMoney.js')
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/jquery-confirm.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/js/jquery.nestable.js')
            ->prependFile($this->basePath() . '/js/jquery.autocomplete.js')
            ->prependFile($this->basePath() . '/js/PowerBI/dist/powerbi.js')
            //->prependFile($this->basePath() . '/js/jquery.colorbox-min.js')
            ->prependFile($this->basePath() . '/js/jquery_sistema_002.js')
            ->prependFile($this->basePath() . '/js/jquery_sistema.js'); ?>
            <script src="https://apis.google.com/js/platform.js"></script>

  </head>
<body>
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KX356LG"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<div id="conteiner" class="<?= $usuario['template'] ?>">
        <nav class="menu nav menu-sistema">
    <div class="fechar-menu">
        <span>
            <svg viewBox="0 0 800 600">
            <path d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200" id="top"></path>
            <path d="M300,320 L540,320" id="middle"></path>
            <path d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190" id="bottom" transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path>
            </svg>
        </span>
    </div>

    <div class="logo">
        <span></span>
    </div>

    <nav>
      <ul class="pmenu" id="nestable3">
        <?php foreach ($menuDashboards as $menu): ?>
          <?php if($menu['dashboards'] == false): ?>
            <li data-id="<?= $menu['id'] ?>">
              <a href="<?= $this->url('visualizarDashboard', array('id' => $menu['id'])); ?>">
                <b class="icon-comment"></b> 
                <span><?= $menu['nome'] ?></span>
              </a>
            </li>
          <?php else: ?>
            <li data-id="cat-<?= $menu['id_categoria'] ?>">
                <a href="#"><b class="icon-comment"></b> <span><?= $menu['nome_categoria'] ?></span></a>
                <ul class="psubmenu">
                  <?php foreach ($menu['dashboards'] as $dashboard): ?>
                    <li data-id="<?= $dashboard['id'] ?>">
                      <a href="<?= $this->url('visualizarDashboard', array('id' => $dashboard['id'])); ?>">
                        <b class="icon-comment"></b> 
                        <span><?= $dashboard['nome'] ?></span>
                      </a>
                    </li>
                  <?php endforeach; ?>
                </ul>
            </li>
          <?php endif; ?>
        <?php endforeach; ?>
        <li>
            <a href="#"><b class="icon-comment"></b> <span>Configurações</span></a>
            <ul class="psubmenu">
                <li>
                  <a href="<?= $this->url('indexCliente'); ?>">
                    <b class="icon-comment"></b> 
                    <span>Clientes</span>
                  </a>
                </li>
                <li>
                  <a href="<?= $this->url('indexCategoria'); ?>">
                    <b class="icon-comment"></b> 
                    <span>Categorias de dash.</span>
                  </a>
                </li>
                <li>
                  <a href="<?= $this->url('indexDashboard'); ?>">
                    <b class="icon-comment"></b> 
                    <span>Dashboards</span>
                  </a>
                </li>
                <li>
                  <a href="<?= $this->url('ordenarMenu', array('id' => $clienteSelecionado['id'])); ?>">
                    <b class="icon-comment"></b> 
                    <span>Ordenar menu</span>
                  </a>
                </li>
                <li>
                  <a href="<?= $this->url('indexInvoice'); ?>">
                    <b class="icon-comment"></b> 
                    <span>Invoices</span>
                  </a>
                </li>
                <li>
                  <a href="<?= $this->url('usuario'); ?>">
                    <b class="icon-comment"></b> 
                    <span>Usuários</span>
                  </a>
                </li>
            </ul>
        </li>
      </ul>
    </nav>

    <div class="botoes-bottom">
        <a class="botao-sair" onclick="signOut();"><b class="icon-logout"></b><span>Sair</span></a>
    </div>

</nav> 




 <div class="cont-admin"><div class="content-sistema"><div class="controle-topo">
    <div class="icones-controle">
        <a href="#"><b class="icon-bell"></b><span>1</span></a>
        <a href="#"><b class="icon-comment"></b></a>
        <a href="#" class="ativar-busca"><b class="icon-search"></b></a>
        <a href="#" class="ligar-luz"><b class="icon-idea-1"></b></a>
        <a onclick="signOut();"><b class="icon-logout"></b></a>
    </div> 

    <div class="nome-logado">
        <h3>
            <?= $usuario['nome'] ?>
            <span><?= $usuario['cargo'] ?></span>
        </h3>
        <div onclick="location.href='<?= $this->url('selecionarCliente'); ?>'">
          <figure>
              <img src="<?= $this->basePath($clienteSelecionado['logo']); ?>">
          </figure>
          
        </div>
    </div>
</div>

<!-- <div class="busca">
    <form action="busca.html" method="post">
        <label>
            <input type="text" name="search_input_field" placeholder="Buscar"> <i class="fas fa-times"></i>
        </label>
    </form>
</div> -->

<div class="conteudo-sistema">
  <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   
  <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>
  <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>
  <?php echo $this->content; ?>
</div>



<script>


    $().ready(function () {
        $('.icones-controle .ativar-busca').click(function () {
            $('.busca form').toggleClass('open');
            $('body').toggleClass('travar');
        });

        $('.busca i').click(function () {
            $('.busca form').toggleClass('open');
            $('body').toggleClass('travar');
        });

        //logout google
        gapi.load('auth2', function() {
          gapi.auth2.init();
        });
    });

</script>

<script>
function signOut() {
      <?php if(isset($usuario['google']) && $usuario['google'] == true): ?>
        gapi.auth2.init();
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          location.href = "<?= $this->url('logout'); ?>";
        });
      <?php else: ?>
        location.href = "<?= $this->url('logout'); ?>";
      <?php endif; ?>
    }
</script> 

       </div>
    </div>
</div>


</body></html>