<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
     <?php echo $this->headTitle($this->loja['nome_restaurante'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/autocomplete.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-confirm.css')
                        ; ?>
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

          <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/maskMoney.js')
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/jquery-confirm.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.autocomplete.js')
            ->prependFile($this->basePath() . '/js/PowerBI/dist/powerbi.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js'); ?>

  </head>
<body>
<div id="conteiner" class="escuro" style="width: 100% !important;">
        <nav class="menu nav menu-sistema">
    <div class="logo">
        <a href="<?= $this->url('indexCliente'); ?>">
          <span style="background-image: url(<?= $this->basePath($clienteSelecionado['logo']); ?>);"></span>
          <h1>Danilo Luna</h1>
        </a>
    </div>
    <ul>
        <li><a href=""><i class="fas fa-home"></i>Principal</a></li>
        <li><a href="<?= $this->url('visualizarDashboard', array('id' => 1)); ?>"><i class="fas fa-angle-right"></i>Dashboard avulsa 1</a></li>
        
        <li><a href="<?= $this->url('indexCategoria') ?>"><i class="fas fa-angle-right"></i>Categorias de dashboard</a></li>
        <li><a href="<?= $this->url('indexCliente'); ?>"><i class="fas fa-angle-right"></i>Clientes</a></li>
        <li><a href="<?= $this->url('indexDashboard') ?>"><i class="fas fa-angle-right"></i>Dashboards</a></li>
        <li><a href="<?= $this->url('indexInvoice') ?>"><i class="fas fa-angle-right"></i>Invoices</a></li>
        <li><a href="<?= $this->url('usuario'); ?>"><i class="fas fa-angle-right"></i>Usuários</a></li>
        <li><hr></li>
        <li><a><i class="fas fa-sign-out-alt"></i>Logout</a></li>
    </ul>
</nav> 

<section class="wrapper-slide">
    <!-- .slideThree -->
    <div class="slideThree">  
        <input class="luz" type="checkbox" value="None" id="slideThree" name="check" checked="checked">
        <label for="slideThree"></label>
    </div>
    <!-- end .slideThree -->
</section>

<?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

<?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>

<?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>

<?php echo $this->content; ?>

</div>


</body>
<script>
    $(function () {
        $('input.luz').on('change', function () {
            if ($(this).is(":checked")) {
                $('#conteiner').addClass('escuro').removeClass('claro');
            } else {
                $('#conteiner').addClass('claro').removeClass('escuro');
            }
        }).trigger('change');
    });
   
</script>


</html>





