<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="google-signin-client_id" content="119263952091-gdpfe1a4arv7dj1g2f4uia1pf517tk44.apps.googleusercontent.com">
     <?php echo $this->headTitle($this->loja['nome_restaurante'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/autocomplete.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-confirm.css')
                        ; ?>
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

          <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/maskMoney.js')
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/jquery-confirm.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/js/jquery.nestable.js')
            ->prependFile($this->basePath() . '/js/jquery.autocomplete.js')
            ->prependFile($this->basePath() . '/js/PowerBI/dist/powerbi.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js'); ?>
          <script src="https://apis.google.com/js/platform.js"></script>

  </head>
<body>
<div id="conteiner" class="escuro" style="width: 100% !important;">
        <nav class="menu nav menu-sistema">
    <div class="logo">
        <a href="<?= $this->url('indexCliente'); ?>">
          <span style="background-image: url(<?= $this->basePath($clienteSelecionado['logo']); ?>);"></span>
          <h1><?= $usuario['nome'] ?></h1>
        </a>
    </div>

    <div class="cf nestable-lists">
        <div class="dd" id="nestable3">
            <ol class="dd-list">
              <?php foreach ($menuDashboards as $menu): ?>
                <?php if($menu['dashboards'] == false): ?>
                  <li class="dd-item dd3-item" data-id="<?= $menu['id'] ?>">
                          <div class="dd-handle dd3-handle"><img src="<?= $this->basePath($menu['icone']); ?>" alt=""></div><div class="dd3-content" onclick="location.href='<?= $this->url('visualizarDashboard', array('id' => $menu['id'])); ?>'"><?= $menu['nome'] ?></div>
                      </li>
                <?php else: ?>

                  <li class="dd-item dd3-item" data-id="cat-<?= $menu['id_categoria'] ?>">
                      <div class="dd-handle dd3-handle"><img src="<?= $this->basePath($menu['icone_categoria']) ?>" alt=""></div><div class="dd3-content"><?= $menu['nome_categoria'] ?></div>
                      <ol class="dd-list">
                        <?php foreach ($menu['dashboards'] as $dashboard): ?>
                            <li class="dd-item dd3-item" data-id="<?= $dashboard['id'] ?>">
                                <div class="dd-handle dd3-handle">
                                  <img src="<?= $this->basePath($dashboard['icone']); ?>" alt="">
                                </div>
                                <div class="dd3-content" onclick="location.href='<?= $this->url('visualizarDashboard', array('id' => $dashboard['id'])); ?>'"><?= $dashboard['nome'] ?></div>
                            </li>
                        <?php endforeach; ?>
                      </ol>
                  </li>
                <?php endif; ?>
              <?php endforeach; ?>
              <li class="dd-item dd3-item" data-id="conf">
                  <div class="dd-handle dd3-handle"><img src="<?= $this->basePath('img/ico-home.png'); ?>" alt=""></div><div class="dd3-content">Configuraçõs</div>
                  <ol class="dd-list">
                      <li class="dd-item dd3-item" data-id="conf-1">
                          <div class="dd-handle dd3-handle">
                            <img src="<?= $this->basePath('img/ico-home.png'); ?>" alt="">
                          </div>
                          <div class="dd3-content" onclick="location.href='<?= $this->url('alterarClienteByCliente'); ?>'">Meus dados</div>
                      </li>
                      <li class="dd-item dd3-item" data-id="conf-4">
                          <div class="dd-handle dd3-handle"><img src="<?= $this->basePath('img/ico-home.png'); ?>" alt=""></div><div class="dd3-content" onclick="location.href='<?= $this->url('indexInvoice'); ?>'">Invoices</div>
                      </li>
                  </ol>
              </li>
              <li class="dd-item dd3-item" data-id="conf-6">
                  <div class="dd-handle dd3-handle"><img src="<?= $this->basePath('img/ico-home.png'); ?>" alt=""></div><div class="dd3-content" onclick="signOut();">Logout</div>
              </li>
            </ol>
        </div> 
    </div>
    
    
</nav> 

<section class="wrapper-slide">
    <!-- .slideThree -->
    <div class="slideThree">  
        <input class="luz" type="checkbox" value="None" id="slideThree" name="check" checked="checked">
        <label for="slideThree"></label>
    </div>
    <!-- end .slideThree -->
</section>
<div class="cont-admin">
  
  <div class="content-sistema">
    
  <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

  <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>

  <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>

<?php echo $this->content; ?>

  </div>
</div>

</div>


</body>
<script>
    $(function () {
        $('input.luz').on('change', function () {
            if ($(this).is(":checked")) {
                $('#conteiner').addClass('escuro').removeClass('claro');
            } else {
                $('#conteiner').addClass('claro').removeClass('escuro');
            }
        }).trigger('change');
    });

    $(document).ready(function(){
      //logout google
      gapi.load('auth2', function() {
        gapi.auth2.init();
      });
    });

    function signOut() {
      <?php if(isset($usuario['google']) && $usuario['google'] == true): ?>
        gapi.auth2.init();
        var auth2 = gapi.auth2.getAuthInstance();
        auth2.signOut().then(function () {
          location.href = "<?= $this->url('logout'); ?>";
        });
      <?php else: ?>
        location.href = "<?= $this->url('logout'); ?>";
      <?php endif; ?>
    }
</script>


</html>