    <h1><a href="<?= $this->url('indexInvoice'); ?>">Invoices</a> / alterar </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoInvoice'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <a href="<?= $this->url('downloadInvoice', array('id' => $invoice['id'])) ?>" class="botao" style="float: right;margin-right: 10px;"><i class="fas fa-download"></i> Download arquivo</a>
      <?php if($invoice['pago'] == 'N'): ?>
      <a onclick="alerta('<?= $this->url('pagarInvoice', array('id' => $invoice['id'])); ?>', 'Tem certeza que deseja marcar o invoice como pago?');" class="botao" style="float: right;margin-right: 10px;"><i class="fas fa-credit-card"></i> Pagar</a>
      <?php endif; ?>
      <br>
      <h2>Alterar invoice do cliente <?= $cliente['nome'] ?></h2>

      <?php echo $this->partial('form/generic', array('form'=> $formInvoice, 'route'=> ''))  ?>

    </div>
