    <h1><i class="fas fa-bars"></i><a href="<?= $this->url('indexInvoice'); ?>">Invoices</a> / alterar </h1>
    <h2>Alterar invoice do cliente <?= $cliente['nome'] ?></h2>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoInvoice'); ?>" class="botao" style="float: right;margin-bottom: 10px;"><i class="far fa-plus-square"></i> Novo</a>
      <a href="<?= $this->url('downloadInvoice', array('id' => $invoice['id'])) ?>" class="botao" style="float: right;margin-right: 10px;margin-bottom: 10px;"><i class="fas fa-download"></i> Download arquivo</a>
      <?php if($invoice['pago'] == 'N'): ?>
      <a onclick="alerta('<?= $this->url('pagarInvoice', array('id' => $invoice['id'])); ?>', 'Tem certeza que deseja marcar o invoice como pago?');" class="botao" style="float: right;margin-right: 10px;"><i class="fas fa-credit-card"></i> Pagar</a>
      
      <a onclick="alerta('<?= $this->url('enviarEmailInvoice', array('id' => $invoice['id'])); ?>', 'Tem certeza que deseja enviar um email para o cliente?');" class="botao" style="float: right;margin-right: 10px;"><i class="fas fa-envelope"></i> Enviar</a>
      
      <?php endif; ?>

      
      <br>

      <?php echo $this->partial('form/generic', array('form'=> $formInvoice, 'route'=> ''))  ?>

    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#valor").maskMoney({symbol:'R$ ', showSymbol:true, thousands:'.', decimal:',', symbolStay: true, allowZero: true});
        $("#data_vencimento").mask("99/99/9999");
      });
    </script>