<div class="container fluid" role="main" style="">
      <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>
    </div>

<div class="container-fluid">
  <div class="row" role="main" style="margin-bottom:10px;padding:0px;">
     <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novoInvoice'); ?>'" style="float: right;width:100px;">
    <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
    Novo</button>
  </div>

    <div class="row">
      <div class="panel panel-primary" style="width: 100%">
        <div class="panel-heading">
          <h3 class="panel-title">Invoices do cliente <?= $cliente['nome'] ?></h3>
        </div>
        <div class="panel-body">
          <?php if($invoices->count() > 0): ?>
            <table class="table">
              <tr>
                <th style="text-align: center">Descrição</th>
                <th style="text-align: center">Valor</th>
                <th style="text-align: center">Data de referência</th>
                <th style="text-align: center">Status</th>
                <th style="text-align: center">Ações</th>
            </tr>
            <?php foreach($invoices as $invoice): ?>
            <tr>
              <td style="text-align: center"><?= $invoice['descricao']; ?></td>
              <td style="text-align: center"><?= $this->exibirMonetario($invoice['valor']); ?></td>
              <td style="text-align: center"><?= $this->converterData($invoice['data_vencimento']); ?></td>
              <td style="text-align: center"><?= $invoice['pago'] == 'S' ? 'Pago' : 'Em aberto' ?></td>
              <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                onclick="location.href='<?= $this->url('alterarInvoice', array('id' => $invoice['id'])); ?>'" style="cursor: pointer;">
                <?php if($invoice['pago'] == 'S'): ?>
                  <span style="margin-right:4px;"></span> 
                    <img src="<?= $this->basePath('img/pago.png'); ?>" title="Invoice pago" style="cursor: pointer;">
                <?php else: ?>
                  <span style="margin-right:4px;"></span> 
                    <img src="<?= $this->basePath('img/pagar.gif'); ?>" title="Pagar invoice"  
                  onclick="alerta('<?= $this->url('pagarInvoice', array('id' => $invoice['id'])); ?>', 'Tem certeza que deseja marcar o invoice como pago?');" style="cursor: pointer;">
                <?php endif; ?>

                <span style="margin-right:4px;"></span> 
                <a href="<?= $this->url('downloadInvoice', array('id' => $invoice['id'])) ?>">
                  <img src="<?= $this->basePath('img/download.png'); ?>" title="Download do arquivo" style="cursor: pointer;">
                </a>
                <span style="margin-right:4px;"></span> 
                  <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" 
                onclick="alerta('<?= $this->url('deletarInvoice', array('id' => $invoice['id'])); ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar o invoice?');" style="cursor: pointer;">
              </td>
            </tr>
            <?php endforeach; ?>
          </table>
        <?php else: ?>
          <div class="alert alert-info">Nenhum invoice encontrado!</div>
        <?php endif; ?>
        </div>
      </div>
    </div>

    <div class="row" style="margin-top:0px;" role="main">
      <div style="float:right;">
        <?php echo $this->paginationControl($invoices,
                                      'Sliding',
                                      'view/paginator', array('route' => 'indexInvoice')); 
        ?>
      </div>
    </div>
  </div>   

    <script type="text/javascript">
      $(document).ready(function() {
        $("#data_inicio").mask("99/99/9999");
        $("#data_fim").mask("99/99/9999");
      });
    </script>