    <h1><a href="<?= $this->url('indexInvoice'); ?>">Invoices</a> / novo </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoInvoice'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <h2>inserir invoice para o cliente <?= $cliente['nome'] ?></h2>
      <?php echo $this->partial('form/generic', array('form'=> $formInvoice, 'route'=> ''))  ?>

    </div>
