    <h1><i class="fas fa-bars"></i><a href="<?= $this->url('indexInvoice'); ?>">Invoices</a> / novo </h1>
    <h2>inserir invoice para o cliente <?= $cliente['nome'] ?></h2>
    <div class="conteudo-sistema">
      <?php echo $this->partial('form/generic', array('form'=> $formInvoice, 'route'=> ''))  ?>

    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#valor").maskMoney({symbol:'R$ ', showSymbol:true, thousands:'.', decimal:',', symbolStay: true, allowZero: true});
        $("#data_vencimento").mask("99/99/9999");
      });
    </script>

    