<div class="cont-admin">
  <div class="content-sistema">
    <h1><a href="<?= $this->url('indexCliente'); ?>">Clientes</a> / alterar </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoCliente'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <br>
      <h2>Alterar cliente</h2>
      <?php echo $this->partial('form/generic', array('form'=> $formCliente, 'route'=> ''))  ?>


      <!-- SUBFORM -->
        <div class="bloco-padrao">
          <a href="<?= $this->url('alterarCliente', array('id' => $cliente['id'])); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo usuário</a>
          <h2>Adicionar ou alterar usuários do cliente <?= $cliente['nome'] ?></h2>
           <?php echo $this->partial('form/generic', array('form'=> $formUsuario, 'route'=> '')) ?>
        </div>

        <div class="bloco-padrao">
          <h2>Usuários do cliente <?= $cliente['nome'] ?></h2>
           
          <?php if($usuarios->count() > 0): ?>
            <table class="table">
              <tbody>
                  <tr class="topo-tabela">
                    <th style="text-align: center">Nome</th>
                    <th style="text-align: center">Email</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
              </tr>
                  </tr>
                  <?php foreach($usuarios as $usuario): ?>
                    <tr>
                        <td style="text-align: center"><?= $usuario['nome']; ?></td>
                        <td style="text-align: center"><?= $usuario['login']; ?></td>
                        <td style="text-align: center"><?= $this->ativo($cliente['ativo']); ?></td>
                        <td style="text-align: center;">
                            <a href="<?= $this->url('alterarCliente', array('id' => $cliente['id'], 'usuario' => $usuario['id'])); ?>" class="bt-editar"><i class="fas fa-edit"></i></a>
                            <a  onclick="alerta('<?= $this->url('deletarUsuarioCliente', array('id' => $cliente['id'], 'usuario' => $usuario['id'])); ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar o usuário?');" class="bt-deletar"><i class="fas fa-minus-circle"></i></a>
                        </td>
                    </tr>
                  <?php endforeach; ?>
              </tbody>
            </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhum usuário encontrado!</div>
            <?php endif; ?>


        </div>
    </div>
  </div>
</div>







    <script type="text/javascript">
      var maskBehavior = function (val) {
       return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      options = {onKeyPress: function(val, e, field, options) {
       field.mask(maskBehavior.apply({}, arguments), options);
       }
      };
       
      $('#telefone').mask(maskBehavior, options);
    </script>