    <h1><i class="fas fa-bars"></i><a href="<?= $this->url('indexCliente'); ?>">Clientes</a> / alterar </h1>
    <h2>Alterar cliente</h2>
    <div class="conteudo-sistema">
      <?php echo $this->partial('form/cliente', array('form'=> $formCliente, 'route'=> ''))  ?>


      <!-- SUBFORM -->
        <div class="bloco-padrao">
          <a id="link-usuario" href="<?= $this->url('alterarUsuarioCliente', array('id' => $cliente['id'])); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo usuário</a>
        </div>
        
        <div class="bloco-padrao">
          <h2>Usuários do cliente <?= $cliente['nome'] ?></h2>
           
          <?php if($usuarios->count() > 0): ?>
            <table class="table">
              <tbody>
                  <tr class="topo-tabela">
                    <th style="text-align: center">Nome</th>
                    <th style="text-align: center">Email</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
              </tr>
                  </tr>
                  <?php foreach($usuarios as $usuario): ?>
                    <tr>
                        <td style="text-align: center"><?= $usuario['nome']; ?></td>
                        <td style="text-align: center"><?= $usuario['login']; ?></td>
                        <td style="text-align: center"><?= $this->ativo($usuario['ativo']); ?></td>
                        <td style="text-align: center;">
                            <a href="<?= $this->url('alterarUsuarioCliente', array('id' => $cliente['id'], 'usuario' => $usuario['id'])); ?>" class="bt-editar" title="Alterar usuário"><i class="fas fa-edit"></i></a>
                            <a  onclick="alerta('<?= $this->url('deletarUsuarioCliente', array('id' => $cliente['id'], 'usuario' => $usuario['id'])); ?>', 'Esta operação é irreversível. Tem certeza que deseja deletar o usuário?');" class="bt-deletar" title="Deletar usuário"><i class="fas fa-minus-circle"></i></a>
                        </td>
                    </tr>
                  <?php endforeach; ?>
              </tbody>
            </table>
            <?php else: ?>
              <br>
              <div class="alert alert-info">Nenhum usuário encontrado!</div>
            <?php endif; ?>


        </div>
    </div>







    <script type="text/javascript">
      var maskBehavior = function (val) {
       return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      options = {onKeyPress: function(val, e, field, options) {
       field.mask(maskBehavior.apply({}, arguments), options);
       }
      };
       
      $('#telefone').mask(maskBehavior, options);
      
      $(document).ready(function() {
        $("#link-usuario").colorbox();

        <?php if($usuario != false): ?>
          <?php if($usuario['pais'] == 'Brasil'): ?>
            $("#p-form-estado_br").css("display", "block");
            $("#p-form-estado").css("display", "none"); 
          <?php else: ?>
            $("#p-form-estado_br").css("display", "none");
            $("#p-form-estado").css("display", "block");
          <?php endif; ?>
        <?php else: ?>
          $("#p-form-estado_br").css("display", "none");
        <?php endif; ?>
        $("#pais").change(function() {
          if(this.value == 'Brasil'){
            $("#p-form-estado_br").css("display", "block");
            $("#p-form-estado").css("display", "none");    
          }else{
            $("#p-form-estado_br").css("display", "none");
            $("#p-form-estado").css("display", "block");
          }
        });
      });
    </script>
    