<div class="bloco-login">
    <div class="logo"></div>
    <?php if($usuario): ?>
      <?php echo $this->partial('form/umacoluna', array('form'=> $formUsuario, 'route'=> '', 'nomeBotao' => 'Ativar conta')) ?>  
    <?php else: ?>
      <div class="alert alert-warning" role="alert">
        Usuário não encontrado, verifique se seu link é válido ou entre em contato com o administrador.
      </div>
    <?php endif; ?>
</div>

<?php if($usuario): ?>
  <script type="text/javascript">
    var maskBehavior = function (val) {
     return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    options = {onKeyPress: function(val, e, field, options) {
     field.mask(maskBehavior.apply({}, arguments), options);
     }
    };
     
    $('#telefone').mask(maskBehavior, options);
  </script>
<?php endif; ?>
