    <h1>Clientes </h1>
    <div class="conteudo-sistema">
      <h2>Pesquisar cliente</h2>
      <?php echo $this->partial('form/pesquisa', array('form'=> $formPesquisa, 'route'=> '')) ?>




      <div class="bloco-padrao">
        <h2>Clientes</h2>
        <?php if($usuario['id_usuario_tipo'] != 2): ?>
          <a href="<?= $this->url('novoCliente'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
          <br>
        <?php endif; ?>
        <?php if($clientes->count() > 0): ?>
        <table class="table">
          <tbody>
              <tr class="topo-tabela">
                  <th style="text-align: center;">Nome</th>
                  <th style="text-align: center">Status</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($clientes as $cliente): ?>
                <tr>
                    <td style="text-align: center"><?= $cliente['nome']; ?></td>
                    <td style="text-align: center"><?= $this->ativo($cliente['ativo']); ?></td>
                    <td style="text-align: center;">
                      <?php if($usuario['id_usuario_tipo'] == 2): ?>
                        <a onclick="alerta('<?= $this->url('selecionarCliente', array('id' => $cliente['id'])); ?>', 'Tem certeza que deseja selecionar o cliente <?= $cliente['nome'] ?>?');" class="bt-selecionar"><i class="fas fa-check-circle"></i></a>
                      <?php else: ?>
                        <a href="<?= $this->url('alterarCliente', array('id' => $cliente['id'])); ?>" class="bt-editar"><i class="fas fa-edit"></i></a>
                        <a onclick="alerta('<?= $this->url('selecionarCliente', array('id' => $cliente['id'])); ?>', 'Tem certeza que deseja selecionar o cliente <?= $cliente['nome'] ?>?');" class="bt-selecionar"><i class="fas fa-check-circle"></i></a>
                        <a onclick="alerta('<?= $this->url('inativarCliente', array('id' => $cliente['id'])); ?>', 'Tem certeza que deseja inativar o cliente <?= $cliente['nome'] ?>?');" class="bt-deletar"><i class="fas fa-minus-circle"></i></a>

                      <?php endif; ?>
                    </td>
                </tr>
              <?php endforeach; ?>
          </tbody>
        </table>
        <?php else: ?>
          <br>
          <div class="alert alert-info">Nenhum cliente encontrado!</div>
        <?php endif; ?>

      </div>

      <div class="paginacao">
          <?php echo $this->paginationControl($clientes,
            'Sliding',
            'view/paginator', array('route' => 'indexCliente')); 
          ?>
      </div>
      

    </div>
<script type="text/javascript">
    //AUTOCOMPLETE CLIENTES
      var clientes = [];
      <?php foreach ($clientesComplete as $cliente) : ?>
        clientes["<?= $cliente['id']; ?>"] = "<?= $cliente['nome'] ?>";
      <?php endforeach; ?>

      //autocomplete
      var clientesArray = $.map(clientes, function (value, key) { return { value: value, data: key }; });

      $('#nome').autocomplete({
        lookup: clientesArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
            /*if($('#telefone').val() == ''){  
              CarregaCliente(suggestion.data, true);
            }*/
        },
        onHint: function (hint) {
            //$('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            //$('#selction-ajax').html('You selected: none');
        }
      });
  </script>




