<div class="cont-admin">
  <div class="content-sistema">
    <h1><a href="<?= $this->url('indexCliente'); ?>">Clientes</a> / novo </h1>
    <div class="conteudo-sistema">
      <a href="<?= $this->url('novoCliente'); ?>" class="botao" style="float: right;"><i class="far fa-plus-square"></i> Novo</a>
      <br>
      <h2>Inserir cliente</h2>

      <?php echo $this->partial('form/generic', array('form'=> $formCliente, 'route'=> ''))  ?>

    </div>
  </div>
</div>